"use client";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Menu from "@/app/components/Never/Menu";
import ThemeButton from "./components/Theme/ThemeButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BlcokChain Talk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <Menu />
          {children}
          <div className="container mx-auto flex justify-end">
            <ThemeButton />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
